In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv("/VGSales.csv")

In [ ]:
df.describe()

,Rank,Year,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
count,16598.000000,16327.000000,16595.000000,16595.000000,16596.000000,16595.000000,16595.000000
mean,8300.605254,2006.406443,0.262117,0.145240,0.077593,0.047969,0.534388
std,4791.853933,5.828981,0.778219,0.488419,0.308308,0.188390,1.528897
min,1.000000,1980.000000,0.000000,0.000000,0.000000,0.000000,0.010000
25%,4151.250000,2003.000000,0.000000,0.000000,0.000000,0.000000,0.060000
50%,8300.500000,2007.000000,0.080000,0.020000,0.000000,0.010000,0.170000
75%,12449.750000,2010.000000,0.240000,0.110000,0.040000,0.040000,0.470000
max,16600.000000,2020.000000,41.490000,29.020000,10.220000,10.570000,82.740000

In [ ]:
df.describe(include='all')

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
count,16598.000000,16598,16598,16327.000000,16598,16540,16595.000000,16595.000000,16596.000000,16595.000000,16595.000000
unique,NaN,11493,31,NaN,12,578,NaN,NaN,NaN,NaN,NaN
top,NaN,Need for Speed: Most Wanted,DS,NaN,Action,Electronic Arts,NaN,NaN,NaN,NaN,NaN
freq,NaN,12,2163,NaN,3316,1351,NaN,NaN,NaN,NaN,NaN
mean,8300.605254,NaN,NaN,2006.406443,NaN,NaN,0.262117,0.145240,0.077593,0.047969,0.534388
std,4791.853933,NaN,NaN,5.828981,NaN,NaN,0.778219,0.488419,0.308308,0.188390,1.528897
min,1.000000,NaN,NaN,1980.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.010000
25%,4151.250000,NaN,NaN,2003.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.060000
50%,8300.500000,NaN,NaN,2007.000000,NaN,NaN,0.080000,0.020000,0.000000,0.010000,0.170000
75%,12449.750000,NaN,NaN,2010.000000,NaN,NaN,0.240000,0.110000,0.040000,0.040000,0.470000
max,16600.000000,NaN,NaN,2020.000000,NaN,NaN,41.490000,29.020000,10.220000,10.570000,82.740000

In [ ]:
df.info()

In [ ]:
df.head(10)

In [ ]:
df.isna()

In [ ]:
df.isnull().sum()

Rank              0
Name              0
Platform          0
Year            271
Genre             0
Publisher        58
NA_Sales          3
EU_Sales          3
JP_Sales          2
Other_Sales       3
Global_Sales      3
dtype: int64

In [ ]:
df.shape

(16598, 11)

In [ ]:
df.isnull().sum().sum()

np.int64(343)

In [ ]:
df.isnull().sum()/ df.size * 100

Rank            0.000000
Name            0.000000
Platform        0.000000
Year            0.148430
Genre           0.000000
Publisher       0.031767
NA_Sales        0.001643
EU_Sales        0.001643
JP_Sales        0.001095
Other_Sales     0.001643
Global_Sales    0.001643
dtype: float64

In [ ]:
df2=df.copy

In [ ]:
df1=df.copy(deep=True)

In [ ]:
#df2.isnull(how='any')

In [ ]:
df.columns

Index(['Rank', 'Name', 'Platform', 'Year', 'Genre', 'Publisher', 'NA_Sales',
       'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales'],
      dtype='object')

In [ ]:
df.dtypes

Rank              int64
Name             object
Platform         object
Year            float64
Genre            object
Publisher        object
NA_Sales        float64
EU_Sales        float64
JP_Sales        float64
Other_Sales     float64
Global_Sales    float64
dtype: object

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.