In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#Loading csv file
df=pd.read_csv('/content/drive/MyDrive/Performance.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Parental_Involvement        6607 non-null   object
 3   Access_to_Resources         6607 non-null   object
 4   Extracurricular_Activities  6607 non-null   object
 5   Sleep_Hours                 6605 non-null   float64
 6   Previous_Scores             6592 non-null   float64
 7   Motivation_Level            6607 non-null   object
 8   Internet_Access             6607 non-null   object
 9   Tutoring_Sessions           6605 non-null   float64
 10  Family_Income               6607 non-null   object
 11  Teacher_Quality             6529 non-null   object
 12  School_Type                 6607 non-null   object
 13  Peer_Influence              6607 non-null   object
 14  Physical_Activity           6604 non-null   float64
 15  Learning_Disabilities       6607 non-null   object
 16  Parental_Education_Level    6516 non-null   object
 17  Distance_from_Home          6540 non-null   object
 18  Gender                      6590 non-null   object
 19  Exam_Score                  6607 non-null   int64
dtypes: float64(4), int64(3), object(13)
memory usage: 1.0+ MB

In [ ]:
df.describe()

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Exam_Score
count,6607.000000,6607.000000,6605.000000,6592.000000,6605.000000,6604.000000,6607.000000
mean,19.975329,80.053125,7.029069,75.100121,1.493868,2.967444,67.296201
std,5.990594,11.889696,1.468239,14.609061,1.230604,1.031240,4.589958
min,1.000000,60.000000,4.000000,50.000000,0.000000,0.000000,55.000000
25%,16.000000,70.000000,6.000000,63.000000,1.000000,2.000000,65.000000
50%,20.000000,80.000000,7.000000,75.000000,1.000000,3.000000,67.000000
75%,24.000000,90.000000,8.000000,88.000000,2.000000,4.000000,69.000000
max,44.000000,198.000000,10.000000,191.000000,8.000000,6.000000,171.000000

In [ ]:
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7.0,73.0,Low,Yes,0.0,Low,Medium,Public,Positive,3.0,No,High School,Near,Male,67
1,19,64,Low,Medium,No,NaN,59.0,Low,Yes,2.0,Medium,Medium,Public,Negative,4.0,No,NaN,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7.0,NaN,Medium,Yes,NaN,Medium,Medium,Public,Neutral,NaN,No,Postgraduate,Near,NaN,74
3,29,89,Low,Medium,Yes,8.0,98.0,Medium,Yes,1.0,Medium,Medium,Public,Negative,4.0,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6.0,65.0,Medium,Yes,3.0,Medium,High,Public,Neutral,4.0,No,College,Near,Female,70

In [ ]:
df.tail()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
6602,25,69,High,Medium,No,7.0,76.0,Medium,Yes,1.0,High,Medium,Public,Positive,0.0,No,High School,Near,Female,68
6603,23,76,High,Medium,No,8.0,81.0,Medium,Yes,3.0,Low,High,Public,Positive,2.0,No,High School,Near,Female,69
6604,20,90,Medium,Low,Yes,6.0,65.0,Low,Yes,3.0,Low,Medium,Public,Negative,2.0,No,Postgraduate,Near,Female,68
6605,10,86,High,High,Yes,0.0,91.0,High,Yes,2.0,Low,Medium,Private,Positive,3.0,No,High School,Far,Female,68
6606,15,67,Medium,Low,Yes,9.0,0.0,Medium,Yes,0.0,Medium,Medium,Public,Positive,0.0,No,Postgraduate,Near,Male,64

In [ ]:
#to check missing values in the datset
df.isnull().sum().sum()

np.int64(275)

In [ ]:
df.fillna({'Sleep_Hours': 0, 'Previous_Scores': 0, 'Tutoring_Sessions': 0,'Teacher_Quality': 'Unknown','Physical_Activity': 0, 'Parental_Education_Level': 'Not_Specified', 'Distance_from_Home': 'Unknown', 'Gender': 'Not_Specified'}, inplace=True)

In [ ]:
df.isna().sum()

Hours_Studied                 0
Attendance                    0
Parental_Involvement          0
Access_to_Resources           0
Extracurricular_Activities    0
Sleep_Hours                   0
Previous_Scores               0
Motivation_Level              0
Internet_Access               0
Tutoring_Sessions             0
Family_Income                 0
Teacher_Quality               0
School_Type                   0
Peer_Influence                0
Physical_Activity             0
Learning_Disabilities         0
Parental_Education_Level      0
Distance_from_Home            0
Gender                        0
Exam_Score                    0
dtype: int64

In [ ]:
df2=df.copy()

In [ ]:
Q1=df2['Exam_Score'].quantile(0.25)
Q2=df2['Exam_Score'].quantile(0.75)
IQR=Q2-Q1

#define lower and upper limit
lower_limit=Q1-1.5*IQR
upper_limit=Q2+1.5*IQR

#Detect Outliers
outliers=df2[(df2['Exam_Score']<lower_limit) | (df2['Exam_Score']>upper_limit)]
print(outliers)

      Hours_Studied  Attendance Parental_Involvement Access_to_Resources  \
5                19         188               Medium              Medium
15               17         168               Medium              Medium
26               13         191                  Low              Medium
45               16         170               Medium              Medium
94               18          89                 High              Medium
...             ...         ...                  ...                 ...
6347             28          96                 High                 Low
6393             16          83                  Low              Medium
6431              4          60               Medium              Medium
6522             18          90                 High                High
6566             29          96                 High              Medium

     Extracurricular_Activities  Sleep_Hours  Previous_Scores  \
5                           Yes          8.0            189.0
15                           No          8.0            170.0
26                           No          6.0            191.0
45                          Yes          8.0            156.0
94                          Yes          4.0             73.0
...                         ...          ...              ...
6347                        Yes          4.0             98.0
6393                        Yes          8.0             92.0
6431                        Yes          7.0             55.0
6522                        Yes          6.0             54.0
6566                         No          8.0             85.0

     Motivation_Level Internet_Access  Tutoring_Sessions Family_Income  \
5              Medium             Yes                3.0        Medium
15             Medium             Yes                2.0        Medium
26             Medium             Yes                1.0          High
45             Medium             Yes                2.0        Medium
94             Medium             Yes                3.0          High
...               ...             ...                ...           ...
6347             High             Yes                1.0          High
6393              Low             Yes                2.0          High
6431           Medium             Yes                2.0           Low
6522              Low             Yes                1.0        Medium
6566              Low             Yes                3.0          High

     Teacher_Quality School_Type Peer_Influence  Physical_Activity  \
5             Medium      Public       Positive                3.0
15            Medium     Private       Positive                4.0
26            Medium      Public       Negative                2.0
45            Medium      Public       Positive                3.0
94            Medium     Private       Positive                2.0
...              ...         ...            ...                ...
6347            High      Public       Positive                3.0
6393            High      Public       Positive                4.0
6431          Medium     Private        Neutral                2.0
6522            High      Public       Negative                3.0
6566          Medium      Public        Neutral                3.0

     Learning_Disabilities Parental_Education_Level Distance_from_Home  \
5                       No             Postgraduate               Near
15                      No              High School               Near
26                     Yes              High School           Moderate
45                      No              High School           Moderate
94                      No                  College               Near
...                    ...                      ...                ...
6347                    No              High School               Near
6393                    No             Postgraduate               Near
6431                    No             Postgraduate               Near
6522                    No              High School               Near
6566                    No             Postgraduate               Near

      Gender  Exam_Score
5       Male         171
15       NaN         164
26    Female         165
45      Male         165
94    Female         100
...      ...         ...
6347    Male          98
6393  Female          98
6431    Male          58
6522  Female          95
6566    Male          76

[108 rows x 20 columns]

In [24]:
df.duplicated().sum()

np.int64(0)

In [28]:
df.Total_outliers=outliers.shape[0]
print(f"")